In [45]:
from bs4 import BeautifulSoup,NavigableString
import requests
import re 
import pandas as pd
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager

import importlib 
from urllib.parse import urljoin, urlparse
import time
import csv
from datetime import datetime
import Utilies
_ChromeDriverManager = ChromeDriverManager().install()

from typing import Optional, Dict, Any

In [3]:
#TO DO
def players_links():
    pass

In [5]:
def Get_Players(url):
    useragent ='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36'
    headers={
        'User-Agent' : useragent,
        'Accept-Language': 'en'
        }
    posts=[]
    page=requests.get(url , headers=headers).text
    soup = BeautifulSoup(page , 'html.parser')
    
    posts.append(
        {
            'player_id': url.split('/')[-1].split('.')[0],
            'player_name': [node.text.strip() for node in soup.select("h1")],
            'Position':[node.text.strip().split('\n\n\n  \n  ▪\n  \n  \n  ') for node in soup.select('#info #meta div p')][[node.text.split()[0] for node in soup.select('#info #meta div p')].index('Position:')][0].strip('Position:'),
            'Shoots':[node.text.strip().split('\n\n\n  \n  ▪\n  \n  \n  ') for node in soup.select('#info #meta div p')][[node.text.split()[0] for node in soup.select('#info #meta div p')].index('Position:')][1].split('Shoots:\n  \n  ')[1],
            'Height':[node.text.split() for node in soup.select('#info #meta div p')][[node.text.split()[0] for node in soup.select('#info #meta div p')].index('Position:')+1][0].replace(',',''),
            'Weight':[node.text.split() for node in soup.select('#info #meta div p')][[node.text.split()[0] for node in soup.select('#info #meta div p')].index('Position:')+1][1].replace('lb',''),
            'Birthday':[node.text.split() for node in soup.select('a[href*=birthdays]')][0][1],
            'Birthmonth':[node.text.split() for node in soup.select('a[href*=birthdays]')][0][0],
            'Birthyear':[node.text.split() for node in soup.select('a[href*=birthyears]')][0],
            'College' : [node.text.split() for node in soup.select('a[href*=colleges]')][0],
            # 'Draft_id': TO Do[node.get_attribute_list('href')[0].split('/')[2] for node in soup.select('a[href*=draft]')][1]
            'Last Season Games':[node.text.split() for node in soup.select('.p1 p')][0],
            'Last Season Points':[node.text.split() for node in soup.select('.p1 p')][2],
            'Last Season Total Rebound Percentage':[node.text.split() for node in soup.select('.p1 p')][4],
            'Last Season Assists Percentage':[node.text.split() for node in soup.select('.p1 p')][6],

            'Last Season Field Goal Percentage':[node.text.split() for node in soup.select('.p1 p')][0],
            'Last Season 3pt Field Goal Percentage':[node.text.split() for node in soup.select('.p1 p')][2],
            'Last Season TFree Throw Percentage':[node.text.split() for node in soup.select('.p1 p')][4],
            'Last Season Effective Field Goal Percentage':[node.text.split() for node in soup.select('.p1 p')][6],

            'Experience':[node.text.split() for node in soup.select('#info #meta div p')][[node.text.split()[0] for node in soup.select('#info #meta div p')].index('Experience:')][1],
            'Career Games':[node.text.split() for node in soup.select('.p1 p')][1],
            'Career Points':[node.text.split() for node in soup.select('.p1 p')][3],
            'Career Total Rebound Percentage':[node.text.split() for node in soup.select('.p1 p')][5],
            'Career Assists Percentage':[node.text.split() for node in soup.select('.p1 p')][7],

            'Career Field Goal Percentage':[node.text.split() for node in soup.select('.p2 p')][1],
            'Career 3pt Field Goal Percentage':[node.text.split() for node in soup.select('.p2 p')][3],
            'Career Free Throw Percentage':[node.text.split() for node in soup.select('.p2 p')][5],
            'Career Effective Field Goal Percentage':[node.text.split() for node in soup.select('.p2 p')][7],

            })
    print(posts)

In [6]:
Get_Players('https://www.basketball-reference.com/players/g/gilgesh01.html')

[{'player_id': 'gilgesh01', 'player_name': ['Shai Gilgeous-Alexander'], 'Position': '\n  \n  Point Guard and Shooting Guard', 'Shoots': 'Right', 'Height': '6-6', 'Weight': '200', 'Birthday': '12', 'Birthmonth': 'July', 'Birthyear': ['1998'], 'College': ['Kentucky'], 'Last Season Games': ['76'], 'Last Season Points': ['32.7'], 'Last Season Total Rebound Percentage': ['5.0'], 'Last Season Assists Percentage': ['6.4'], 'Last Season Field Goal Percentage': ['76'], 'Last Season 3pt Field Goal Percentage': ['32.7'], 'Last Season TFree Throw Percentage': ['5.0'], 'Last Season Effective Field Goal Percentage': ['6.4'], 'Experience': '7', 'Career Games': ['462'], 'Career Points': ['24.4'], 'Career Total Rebound Percentage': ['4.8'], 'Career Assists Percentage': ['5.1'], 'Career Field Goal Percentage': ['50.1'], 'Career 3pt Field Goal Percentage': ['35.5'], 'Career Free Throw Percentage': ['86.2'], 'Career Effective Field Goal Percentage': ['54.0']}]

In [7]:
def Get_MVPs(url):
    useragent ='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36'
    headers={
        'User-Agent' : useragent,
        'Accept-Language': 'en'
        }
    posts=[]
    page=requests.get(url , headers=headers).text
    soup = BeautifulSoup(page , 'html.parser')
    for i in range(70):
        posts.append(
            {
                'Season':[node.text.strip() for node in soup.select(f"#mvp_NBA > tbody > tr:nth-child({i+1}) > th")],
                'League':'NBA',
                'Player_id':[node.get_attribute_list('href')[0].split('/')[-1].split('.')[0] for node in soup.select(f"a[href*='players']")][i+1],
                'Age': [node.text.strip() for node in soup.select(f"#mvp_NBA > tbody > tr:nth-child({i+1}) > td:nth-child(5)")],
                'Team_id': [node.text.strip() for node in soup.select(f"#mvp_NBA > tbody > tr:nth-child({i+1}) > td:nth-child(6)")],
                'Game': [node.text.strip() for node in soup.select(f"#mvp_NBA > tbody > tr:nth-child({i+1}) > td:nth-child(7)")],
                'Minutes Played Per Game':[node.text.strip() for node in soup.select(f"#mvp_NBA > tbody > tr:nth-child({i+1}) > td:nth-child(8)")],
                'Points Per Game':[node.text.strip() for node in soup.select(f"#mvp_NBA > tbody > tr:nth-child({i+1}) > td:nth-child(9)")],
                'Total Rebounds Per Game':[node.text.strip() for node in soup.select(f"#mvp_NBA > tbody > tr:nth-child({i+1}) > td:nth-child(10)")],
                'Assists Per Game':[node.text.strip() for node in soup.select(f"#mvp_NBA > tbody > tr:nth-child({i+1}) > td:nth-child(11)")],
                'Steals Per Game':[node.text.strip() for node in soup.select(f"#mvp_NBA > tbody > tr:nth-child({i+1}) > td:nth-child(12)")],
                'Blocks Per Game':[node.text.strip() for node in soup.select(f"#mvp_NBA > tbody > tr:nth-child({i+1}) > td:nth-child(13)")],
                'Field Goal Percentage':[node.text.strip() for node in soup.select(f"#mvp_NBA > tbody > tr:nth-child({i+1}) > td:nth-child(14)")],
                '3-Point Field Goal Percentage':[node.text.strip() for node in soup.select(f"#mvp_NBA > tbody > tr:nth-child({i+1}) > td:nth-child(15)")],
                'Free Throw Percentage':[node.text.strip() for node in soup.select(f"#mvp_NBA > tbody > tr:nth-child({i+1}) > td:nth-child(16)")],
                'Win Shares':[node.text.strip() for node in soup.select(f"#mvp_NBA > tbody > tr:nth-child({i+1}) > td:nth-child(17)")],
                'Win Shares Per 48 Minutes':[node.text.strip() for node in soup.select(f"#mvp_NBA > tbody > tr:nth-child({i+1}) > td:nth-child(18)")],
             }
        )

    return posts

In [8]:
Mvp_Data=[]
Mvp_Data.append(Utilies.Get_MVPs('https://www.basketball-reference.com/awards/mvp.html'))

Mvp_Df=pd.DataFrame(Mvp_Data[0])

In [9]:
def make_df_pretty(dataframe):
    for i in dataframe.columns:
        if type(dataframe[i][0]) is list: 
            dataframe[i]=dataframe[i].apply(lambda lst : list(dict.fromkeys(lst)))
            dataframe[i]=dataframe[i].apply(lambda x: ",".join(map(str,x)))

In [10]:
importlib.reload(Utilies)

In [11]:
Utilies.make_df_pretty(Mvp_Df)

In [12]:
Mvp_Df=Mvp_Df.replace('', pd.NA)

In [13]:
Mvp_Df

,Season,League,Player_id,Age,Team_id,Game,Minutes Played Per Game,Points Per Game,Total Rebounds Per Game,Assists Per Game,Steals Per Game,Blocks Per Game,Field Goal Percentage,3-Point Field Goal Percentage,Free Throw Percentage,Win Shares,Win Shares Per 48 Minutes
0,2024-25,NBA,gilgesh01,26,OKC,76,34.2,32.7,5.0,6.4,1.7,1.0,.519,.375,.898,16.7,.309
1,2023-24,NBA,jokicni01,28,DEN,79,34.6,26.4,12.4,9.0,1.4,0.9,.583,.359,.817,17.0,.299
2,2022-23,NBA,embiijo01,28,PHI,66,34.6,33.1,10.2,4.2,1.0,1.7,.548,.330,.857,12.3,.259
3,2021-22,NBA,jokicni01,26,DEN,74,33.5,27.1,13.8,7.9,1.5,0.9,.583,.337,.810,15.2,.296
4,2020-21,NBA,jokicni01,25,DEN,72,34.6,26.4,10.8,8.3,1.3,0.7,.566,.388,.868,15.6,.301
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,1959-60,NBA,chambwi01,23,PHW,72,46.4,37.6,27.0,2.3,<NA>,<NA>,.461,<NA>,.582,17.0,.245
66,1958-59,NBA,pettibo01,26,STL,72,39.9,29.2,16.4,3.1,<NA>,<NA>,.438,<NA>,.759,14.8,.246
67,1957-58,NBA,russebi01,23,BOS,69,38.3,16.6,22.7,2.9,<NA>,<NA>,.442,<NA>,.519,11.3,.206
68,1956-57,NBA,cousybo01,28,BOS,64,36.9,20.6,4.8,7.5,<NA>,<NA>,.378,<NA>,.821,8.8,.178
69,1955-56,NBA,pettibo01,23,STL,72,38.8,25.7,16.2,2.6,<NA>,<NA>,.429,<NA>,.736,13.8,.236

In [68]:
def save_results_csv(results,fieldnames, fname="data/teams_link.csv"):
    with open(fname, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames
        )
        writer.writeheader()
        for r in results:
            writer.writerow(r)
    print(f"[INFO] Saved {len(results)} rows to {fname}")

In [ ]:
def normalized(url):
    p = urlparse(url)
    return p._replace(fragment="").geturl()

def GetTeams (url):
    REQUEST_DELAY=0.8
    useragent ='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36'
    headers={
        'User-Agent' : useragent,
        'Accept-Language': 'en'
        }
    teams=[]

        
    useragent ='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36'
    headers={
        'User-Agent' : useragent,
        'Accept-Language': 'en'
        }
    # posts=[]
    page=requests.get(url , headers=headers).text
    soup = BeautifulSoup(page , 'html.parser')
    
    # soup = BeautifulSoup(html , 'html.parser')
    
    teamlinks = soup.find_all('a',href=re.compile(r"^/teams"))
    print(teamlinks)
    start_url ='https://www.basketball-reference.com/'
    
    for item in teamlinks:
        teams.append(
            {
                "TeamName":item.get_text(strip=False),
                "Link":urljoin(normalized(start_url), item["href"])
            }
    )
    save_results_csv(teams,[
                "TeamName",
                "Link",
            ],'data/teams_link.csv')

    return teams


teams =GetTeams('https://www.basketball-reference.com/leagues/')

[<a href="/teams/">Teams</a>, <a href="/teams/OKC/2025.html">Oklahoma City Thunder</a>, <a href="/teams/BOS/2024.html">Boston Celtics</a>, <a href="/teams/DEN/2023.html">Denver Nuggets</a>, <a href="/teams/GSW/2022.html">Golden State Warriors</a>, <a href="/teams/MIL/2021.html">Milwaukee Bucks</a>, <a href="/teams/LAL/2020.html">Los Angeles Lakers</a>, <a href="/teams/TOR/2019.html">Toronto Raptors</a>, <a href="/teams/GSW/2018.html">Golden State Warriors</a>, <a href="/teams/GSW/2017.html">Golden State Warriors</a>, <a href="/teams/CLE/2016.html">Cleveland Cavaliers</a>, <a href="/teams/GSW/2015.html">Golden State Warriors</a>, <a href="/teams/SAS/2014.html">San Antonio Spurs</a>, <a href="/teams/MIA/2013.html">Miami Heat</a>, <a href="/teams/MIA/2012.html">Miami Heat</a>, <a href="/teams/DAL/2011.html">Dallas Mavericks</a>, <a href="/teams/LAL/2010.html">Los Angeles Lakers</a>, <a href="/teams/LAL/2009.html">Los Angeles Lakers</a>, <a href="/teams/BOS/2008.html">Boston Celtics</a>, <a href="/teams/SAS/2007.html">San Antonio Spurs</a>, <a href="/teams/MIA/2006.html">Miami Heat</a>, <a href="/teams/SAS/2005.html">San Antonio Spurs</a>, <a href="/teams/DET/2004.html">Detroit Pistons</a>, <a href="/teams/SAS/2003.html">San Antonio Spurs</a>, <a href="/teams/LAL/2002.html">Los Angeles Lakers</a>, <a href="/teams/LAL/2001.html">Los Angeles Lakers</a>, <a href="/teams/LAL/2000.html">Los Angeles Lakers</a>, <a href="/teams/SAS/1999.html">San Antonio Spurs</a>, <a href="/teams/CHI/1998.html">Chicago Bulls</a>, <a href="/teams/CHI/1997.html">Chicago Bulls</a>, <a href="/teams/CHI/1996.html">Chicago Bulls</a>, <a href="/teams/HOU/1995.html">Houston Rockets</a>, <a href="/teams/HOU/1994.html">Houston Rockets</a>, <a href="/teams/CHI/1993.html">Chicago Bulls</a>, <a href="/teams/CHI/1992.html">Chicago Bulls</a>, <a href="/teams/CHI/1991.html">Chicago Bulls</a>, <a href="/teams/DET/1990.html">Detroit Pistons</a>, <a href="/teams/DET/1989.html">Detroit Pistons</a>, <a href="/teams/LAL/1988.html">Los Angeles Lakers</a>, <a href="/teams/LAL/1987.html">Los Angeles Lakers</a>, <a href="/teams/BOS/1986.html">Boston Celtics</a>, <a href="/teams/LAL/1985.html">Los Angeles Lakers</a>, <a href="/teams/BOS/1984.html">Boston Celtics</a>, <a href="/teams/PHI/1983.html">Philadelphia 76ers</a>, <a href="/teams/LAL/1982.html">Los Angeles Lakers</a>, <a href="/teams/BOS/1981.html">Boston Celtics</a>, <a href="/teams/LAL/1980.html">Los Angeles Lakers</a>, <a href="/teams/SEA/1979.html">Seattle SuperSonics</a>, <a href="/teams/WSB/1978.html">Washington Bullets</a>, <a href="/teams/POR/1977.html">Portland Trail Blazers</a>, <a href="/teams/BOS/1976.html">Boston Celtics</a>, <a href="/teams/NYA/1976.html">New York Nets</a>, <a href="/teams/GSW/1975.html">Golden State Warriors</a>, <a href="/teams/KEN/1975.html">Kentucky Colonels</a>, <a href="/teams/BOS/1974.html">Boston Celtics</a>, <a href="/teams/NYA/1974.html">New York Nets</a>, <a href="/teams/NYK/1973.html">New York Knicks</a>, <a href="/teams/INA/1973.html">Indiana Pacers</a>, <a href="/teams/LAL/1972.html">Los Angeles Lakers</a>, <a href="/teams/INA/1972.html">Indiana Pacers</a>, <a href="/teams/MIL/1971.html">Milwaukee Bucks</a>, <a href="/teams/UTS/1971.html">Utah Stars</a>, <a href="/teams/NYK/1970.html">New York Knicks</a>, <a href="/teams/INA/1970.html">Indiana Pacers</a>, <a href="/teams/BOS/1969.html">Boston Celtics</a>, <a href="/teams/OAK/1969.html">Oakland Oaks</a>, <a href="/teams/BOS/1968.html">Boston Celtics</a>, <a href="/teams/PTP/1968.html">Pittsburgh Pipers</a>, <a href="/teams/PHI/1967.html">Philadelphia 76ers</a>, <a href="/teams/BOS/1966.html">Boston Celtics</a>, <a href="/teams/BOS/1965.html">Boston Celtics</a>, <a href="/teams/BOS/1964.html">Boston Celtics</a>, <a href="/teams/BOS/1963.html">Boston Celtics</a>, <a href="/teams/BOS/1962.html">Boston Celtics</a>, <a href="/teams/BOS/1961.html">Boston Celtics</a>, <a href="/teams/BOS/1960.html">Boston Celtics</a>, <a href="/teams/BOS/1959.html">Boston Celtics</a>, <a href="/teams/STL/1958.html">St. Louis Hawks</a>, <a href="/teams/BOS/1957.html">Boston Celtics</a>, <a href="/teams/PHW/1956.html">Philadelphia Warriors</a>, <a href="/teams/SYR/1955.html">Syracuse Nationals</a>, <a href="/teams/MNL/1954.html">Minneapolis Lakers</a>, <a href="/teams/MNL/1953.html">Minneapolis Lakers</a>, <a href="/teams/MNL/1952.html">Minneapolis Lakers</a>, <a href="/teams/ROC/1951.html">Rochester Royals</a>, <a href="/teams/MNL/1950.html">Minneapolis Lakers</a>, <a href="/teams/MNL/1949.html">Minneapolis Lakers</a>, <a href="/teams/BLB/1948.html">Baltimore Bullets</a>, <a href="/teams/PHW/1947.html">Philadelphia Warriors</a>, <a href="/teams/">Teams</a>, <a href="/teams/TOR/2026.html">Toronto</a>, <a href="/teams/BOS/2026.html">Boston</a>, <a href="/teams/NYK/2026.html">New York</a>, <a href="/teams/BRK/2026.html">Brooklyn</a>, <a href="/teams/PHI/2026.html">Philadelphia</a>, <a href="/teams/CLE/2026.html">Cleveland</a>, <a href="/teams/IND/2026.html">Indiana</a>, <a href="/teams/DET/2026.html">Detroit</a>, <a href="/teams/CHI/2026.html">Chicago</a>, <a href="/teams/MIL/2026.html">Milwaukee</a>, <a href="/teams/MIA/2026.html">Miami</a>, <a href="/teams/ATL/2026.html">Atlanta</a>, <a href="/teams/CHO/2026.html">Charlotte</a>, <a href="/teams/WAS/2026.html">Washington</a>, <a href="/teams/ORL/2026.html">Orlando</a>, <a href="/teams/OKC/2026.html">Oklahoma City</a>, <a href="/teams/POR/2026.html">Portland</a>, <a href="/teams/UTA/2026.html">Utah</a>, <a href="/teams/DEN/2026.html">Denver</a>, <a href="/teams/MIN/2026.html">Minnesota</a>, <a href="/teams/GSW/2026.html">Golden State</a>, <a href="/teams/LAC/2026.html">Los Angeles Clippers</a>, <a href="/teams/SAC/2026.html">Sacramento</a>, <a href="/teams/PHO/2026.html">Phoenix</a>, <a href="/teams/LAL/2026.html">Los Angeles Lakers</a>, <a href="/teams/SAS/2026.html">San Antonio</a>, <a href="/teams/DAL/2026.html">Dallas</a>, <a href="/teams/MEM/2026.html">Memphis</a>, <a href="/teams/HOU/2026.html">Houston</a>, <a href="/teams/NOP/2026.html">New Orleans</a>, <a href="/teams/BOS/2025_games.html">Team Schedules</a>]
[INFO] Saved 121 rows to data/teams_link.csv

In [18]:
def _to_snake(s: str) -> str:
    s = s.strip()
    s = s.rstrip(":")
    s = re.sub(r"[^\w]+", "_", s)
    s = re.sub(r"__+", "_", s)
    return s.strip("_").lower()

def _try_int(v: str) -> Any:
    v_stripped = v.replace(",", "").strip()
    if re.fullmatch(r"\d+", v_stripped):
        return int(v_stripped)
    return v

def _parse_seasons(value: str) -> Dict[str, Optional[Any]]:
    parts = [p.strip() for p in value.split(";") if p.strip()]
    out = {"raw": value, "count": None, "range": None}
    if not parts:
        return out
    m = re.match(r"^(\d+)$", parts[0])
    if m:
        out["count"] = int(m.group(1))
        if len(parts) > 1:
            out["range"] = parts[1]
    else:
        if len(parts) == 1 and re.search(r"\d{4}", parts[0]):
            out["range"] = parts[0]
    return out

In [ ]:
import random

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0) AppleWebKit/605.1.15 "
    "(KHTML, like Gecko) Version/16.0 Safari/605.1.15",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/116.0.5845.96 Safari/537.36",
]


def fetch_page(url, session, max_retries=5, delay=3,way=1):
    

    for attempt in range(1, max_retries + 1):
        ua = random.choice(USER_AGENTS)
        if way == 1:
            session.headers.update({"User-Agent": ua})
        else:
            chrome_options = Options()
            chrome_options.add_argument("--headless")
            chrome_options.add_argument("--disable-gpu")
            chrome_options.add_argument(f"user-agent={ua}")
            chrome_options.add_argument("--no-sandbox")
            chrome_options.add_argument("--disable-blink-features=AutomationControlled")
        
        try:
            if way != 1:
                driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)
                driver.get(url)

                time.sleep(delay + random.uniform(0, 2))

                html = driver.page_source
                driver.quit()
                return html
            else:
                resp = session.get(url, timeout=30)
                if resp.status_code == 429:
                    wait = delay + random.uniform(0, 2)
                    print(f"[WARN] 429 Too Many Requests. Waiting {wait:.1f}s (attempt {attempt})")
                    time.sleep(wait)
                    continue
                resp.raise_for_status()
                time.sleep(delay)  
                return resp.text

            
        except Exception as e:
            if way == 1:
                wait = delay + random.uniform(0, 2)
                print(f"[WARN] Request failed ({e}). Retrying in {wait:.1f}s (attempt {attempt})")
                time.sleep(wait)
                print(f"[ERROR] Failed to fetch {url} after {max_retries} attempts.")
            else:
                print(f"[WARN] Selenium fetch failed ({e}). Retrying in {delay:.1f}s (attempt {attempt})")
                time.sleep(delay + random.uniform(0, 2))
                try:
                    driver.quit()
                except:
                    pass
                print(f"[ERROR] Failed to fetch {url} after {max_retries} attempts with Selenium.")

    return None

In [ ]:
seen = []

def GetTeamDetail (team):
    session = requests.Session()
    session.headers.update({
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                    "(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36",
        "Accept-Language": "en-US,en;q=0.9"
    })


    url =team['Link']
    parsed = urlparse(url)
    parts = parsed.path.split("/")
    base_path = "/".join(parts[:3]) 
    href = f"{parsed.scheme}://{parsed.netloc}{base_path}"
    if href in seen:
        return None
    
    html = fetch_page(href, session,way=2)
    if html is None:
        return {
            "link":href
        }

    
    soup = BeautifulSoup(html , 'html.parser')
    seen.append(href)
    meta = None
    meta = soup.select_one("#info > #meta")
    result = {"link":href}
    if meta is None:
        return {"link":href}
    
    title_span = meta.select_one('h1 span') 
    result["team_full_name"] = title_span.get_text(strip=True) if title_span else None 
    
    for p in meta.select("p"):
        strong = p.find("strong")
        if not strong:
            continue

        label = strong.get_text(strip=True).rstrip(":")
        key = _to_snake(label)   
        
        parts = []
        for sib in strong.next_siblings:
            if isinstance(sib, NavigableString):
                txt = str(sib)
            else:
                txt = sib.get_text(separator=" ", strip=True)
            if txt and txt != "\n":
                parts.append(txt)
        raw_value = " ".join(parts)
        value = re.sub(r"\s+", " ", raw_value).strip()
        value = value.strip(" ;:\n\t,")

        coerced = _try_int(value)

        result[key] = coerced
        if key == 'team_name':
            result['team_names'] = coerced
            del result['team_name']
        if key == "seasons":
            parsed = _parse_seasons(value)
            result["seasons_count"] = parsed.get("count")
            result["seasons_range"] = parsed.get("range")



    
   
    return result
    
teams_filterd = [d for d in teams if d.get("TeamName") != "F" and d.get("TeamName") != "Teams"]

team_details = []


counter = 0
for team in teams_filterd:
    # if counter > 4:
    #     break
    res = GetTeamDetail(team)
    if(res != None):
        team_details.append(res)
        save_results_csv(team_details,[
                "link",
                "team_full_name",
                "location",
                "team_names",
                'seasons',
                'seasons_count',
                'seasons_range',
                'record',
                'playoff_appearances',
                'championships'
            ],'data/teams2.csv')
    counter = counter+1


team_details

https://www.basketball-reference.com/teams/OKC ['https://www.basketball-reference.com/teams/OKC']
[INFO] Saved 1 rows to data/teams2.csv
https://www.basketball-reference.com/teams/BOS ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS']
[INFO] Saved 2 rows to data/teams2.csv
https://www.basketball-reference.com/teams/DEN ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN']
[INFO] Saved 3 rows to data/teams2.csv
https://www.basketball-reference.com/teams/GSW ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW']
[INFO] Saved 4 rows to data/teams2.csv
https://www.basketball-reference.com/teams/MIL ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL']
[INFO] Saved 5 rows to data/teams2.csv
https://www.basketball-reference.com/teams/LAL ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL']
[INFO] Saved 6 rows to data/teams2.csv
https://www.basketball-reference.com/teams/TOR ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL', 'https://www.basketball-reference.com/teams/TOR']
[INFO] Saved 7 rows to data/teams2.csv
https://www.basketball-reference.com/teams/CLE ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL', 'https://www.basketball-reference.com/teams/TOR', 'https://www.basketball-reference.com/teams/CLE']
[INFO] Saved 8 rows to data/teams2.csv
https://www.basketball-reference.com/teams/SAS ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL', 'https://www.basketball-reference.com/teams/TOR', 'https://www.basketball-reference.com/teams/CLE', 'https://www.basketball-reference.com/teams/SAS']
[INFO] Saved 9 rows to data/teams2.csv
https://www.basketball-reference.com/teams/MIA ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL', 'https://www.basketball-reference.com/teams/TOR', 'https://www.basketball-reference.com/teams/CLE', 'https://www.basketball-reference.com/teams/SAS', 'https://www.basketball-reference.com/teams/MIA']
[INFO] Saved 10 rows to data/teams2.csv
https://www.basketball-reference.com/teams/DAL ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL', 'https://www.basketball-reference.com/teams/TOR', 'https://www.basketball-reference.com/teams/CLE', 'https://www.basketball-reference.com/teams/SAS', 'https://www.basketball-reference.com/teams/MIA', 'https://www.basketball-reference.com/teams/DAL']
[INFO] Saved 11 rows to data/teams2.csv
https://www.basketball-reference.com/teams/DET ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL', 'https://www.basketball-reference.com/teams/TOR', 'https://www.basketball-reference.com/teams/CLE', 'https://www.basketball-reference.com/teams/SAS', 'https://www.basketball-reference.com/teams/MIA', 'https://www.basketball-reference.com/teams/DAL', 'https://www.basketball-reference.com/teams/DET']
[INFO] Saved 12 rows to data/teams2.csv
https://www.basketball-reference.com/teams/CHI ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL', 'https://www.basketball-reference.com/teams/TOR', 'https://www.basketball-reference.com/teams/CLE', 'https://www.basketball-reference.com/teams/SAS', 'https://www.basketball-reference.com/teams/MIA', 'https://www.basketball-reference.com/teams/DAL', 'https://www.basketball-reference.com/teams/DET', 'https://www.basketball-reference.com/teams/CHI']
[INFO] Saved 13 rows to data/teams2.csv
https://www.basketball-reference.com/teams/HOU ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL', 'https://www.basketball-reference.com/teams/TOR', 'https://www.basketball-reference.com/teams/CLE', 'https://www.basketball-reference.com/teams/SAS', 'https://www.basketball-reference.com/teams/MIA', 'https://www.basketball-reference.com/teams/DAL', 'https://www.basketball-reference.com/teams/DET', 'https://www.basketball-reference.com/teams/CHI', 'https://www.basketball-reference.com/teams/HOU']
[INFO] Saved 14 rows to data/teams2.csv
https://www.basketball-reference.com/teams/PHI ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL', 'https://www.basketball-reference.com/teams/TOR', 'https://www.basketball-reference.com/teams/CLE', 'https://www.basketball-reference.com/teams/SAS', 'https://www.basketball-reference.com/teams/MIA', 'https://www.basketball-reference.com/teams/DAL', 'https://www.basketball-reference.com/teams/DET', 'https://www.basketball-reference.com/teams/CHI', 'https://www.basketball-reference.com/teams/HOU', 'https://www.basketball-reference.com/teams/PHI']
[INFO] Saved 15 rows to data/teams2.csv
https://www.basketball-reference.com/teams/SEA ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL', 'https://www.basketball-reference.com/teams/TOR', 'https://www.basketball-reference.com/teams/CLE', 'https://www.basketball-reference.com/teams/SAS', 'https://www.basketball-reference.com/teams/MIA', 'https://www.basketball-reference.com/teams/DAL', 'https://www.basketball-reference.com/teams/DET', 'https://www.basketball-reference.com/teams/CHI', 'https://www.basketball-reference.com/teams/HOU', 'https://www.basketball-reference.com/teams/PHI', 'https://www.basketball-reference.com/teams/SEA']
[INFO] Saved 16 rows to data/teams2.csv
[WARN] Selenium fetch failed (response body:
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>We're sorry, but this service is not available in your location</Details></Error>
request url:
https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/mac-arm64/chromedriver-mac-arm64.zip
response headers:
{'Content-Type': 'application/xml; charset=UTF-8', 'X-GUploader-UploadID': 'AAwnv3J2TGPhVl4-PX6pQV5LhjjNwQjudpDOXoHdXa0ujXA66Et5Rq0HW1E2jhxDrn--_31WwQ716uA', 'Content-Length': '193', 'Date': 'Wed, 24 Sep 2025 20:30:58 GMT', 'Expires': 'Wed, 24 Sep 2025 20:30:58 GMT', 'Cache-Control': 'private, max-age=0', 'Server': 'UploadServer', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'}
). Retrying in 3.0s (attempt 1)
[ERROR] Failed to fetch https://www.basketball-reference.com/teams/WSB after 5 attempts with Selenium.
[WARN] Selenium fetch failed (response body:
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>We're sorry, but this service is not available in your location</Details></Error>
request url:
https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/mac-arm64/chromedriver-mac-arm64.zip
response headers:
{'Content-Type': 'application/xml; charset=UTF-8', 'X-GUploader-UploadID': 'AAwnv3Kquze7PVkuEjEtjK5ap4w3gzcTrTL9mdrOrMjreD7S1uqqFK9RZcLO3cPl5g8WTDBt5OZqfsI', 'Content-Length': '193', 'Date': 'Wed, 24 Sep 2025 20:31:06 GMT', 'Expires': 'Wed, 24 Sep 2025 20:31:06 GMT', 'Cache-Control': 'private, max-age=0', 'Server': 'UploadServer', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'}
). Retrying in 3.0s (attempt 2)
[ERROR] Failed to fetch https://www.basketball-reference.com/teams/WSB after 5 attempts with Selenium.
[WARN] Selenium fetch failed (response body:
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>We're sorry, but this service is not available in your location</Details></Error>
request url:
https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/mac-arm64/chromedriver-mac-arm64.zip
response headers:
{'Content-Type': 'application/xml; charset=UTF-8', 'X-GUploader-UploadID': 'AAwnv3IW_Q4lreMmZCmWKwFcmhuozpZTwH1nM1MimberOOzt8MrV7J406u9xvT6hCE2x7p5Z', 'Content-Length': '193', 'Date': 'Wed, 24 Sep 2025 20:31:14 GMT', 'Expires': 'Wed, 24 Sep 2025 20:31:14 GMT', 'Cache-Control': 'private, max-age=0', 'Server': 'UploadServer', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'}
). Retrying in 3.0s (attempt 3)
[ERROR] Failed to fetch https://www.basketball-reference.com/teams/WSB after 5 attempts with Selenium.
[WARN] Selenium fetch failed (response body:
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>We're sorry, but this service is not available in your location</Details></Error>
request url:
https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/mac-arm64/chromedriver-mac-arm64.zip
response headers:
{'Content-Type': 'application/xml; charset=UTF-8', 'X-GUploader-UploadID': 'AAwnv3JayctxpEiDrICAujceUEjn9S8SUi5C8E6rUxJrZXXoaRzXJBiu8caNwCu14OdUVu81', 'Content-Length': '193', 'Date': 'Wed, 24 Sep 2025 20:31:21 GMT', 'Expires': 'Wed, 24 Sep 2025 20:31:21 GMT', 'Cache-Control': 'private, max-age=0', 'Server': 'UploadServer', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'}
). Retrying in 3.0s (attempt 4)
[ERROR] Failed to fetch https://www.basketball-reference.com/teams/WSB after 5 attempts with Selenium.
https://www.basketball-reference.com/teams/WSB ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL', 'https://www.basketball-reference.com/teams/TOR', 'https://www.basketball-reference.com/teams/CLE', 'https://www.basketball-reference.com/teams/SAS', 'https://www.basketball-reference.com/teams/MIA', 'https://www.basketball-reference.com/teams/DAL', 'https://www.basketball-reference.com/teams/DET', 'https://www.basketball-reference.com/teams/CHI', 'https://www.basketball-reference.com/teams/HOU', 'https://www.basketball-reference.com/teams/PHI', 'https://www.basketball-reference.com/teams/SEA', 'https://www.basketball-reference.com/teams/WSB']
[INFO] Saved 17 rows to data/teams2.csv
https://www.basketball-reference.com/teams/POR ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL', 'https://www.basketball-reference.com/teams/TOR', 'https://www.basketball-reference.com/teams/CLE', 'https://www.basketball-reference.com/teams/SAS', 'https://www.basketball-reference.com/teams/MIA', 'https://www.basketball-reference.com/teams/DAL', 'https://www.basketball-reference.com/teams/DET', 'https://www.basketball-reference.com/teams/CHI', 'https://www.basketball-reference.com/teams/HOU', 'https://www.basketball-reference.com/teams/PHI', 'https://www.basketball-reference.com/teams/SEA', 'https://www.basketball-reference.com/teams/WSB', 'https://www.basketball-reference.com/teams/POR']
[INFO] Saved 18 rows to data/teams2.csv
https://www.basketball-reference.com/teams/NYA ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL', 'https://www.basketball-reference.com/teams/TOR', 'https://www.basketball-reference.com/teams/CLE', 'https://www.basketball-reference.com/teams/SAS', 'https://www.basketball-reference.com/teams/MIA', 'https://www.basketball-reference.com/teams/DAL', 'https://www.basketball-reference.com/teams/DET', 'https://www.basketball-reference.com/teams/CHI', 'https://www.basketball-reference.com/teams/HOU', 'https://www.basketball-reference.com/teams/PHI', 'https://www.basketball-reference.com/teams/SEA', 'https://www.basketball-reference.com/teams/WSB', 'https://www.basketball-reference.com/teams/POR', 'https://www.basketball-reference.com/teams/NYA']
[INFO] Saved 19 rows to data/teams2.csv
https://www.basketball-reference.com/teams/KEN ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL', 'https://www.basketball-reference.com/teams/TOR', 'https://www.basketball-reference.com/teams/CLE', 'https://www.basketball-reference.com/teams/SAS', 'https://www.basketball-reference.com/teams/MIA', 'https://www.basketball-reference.com/teams/DAL', 'https://www.basketball-reference.com/teams/DET', 'https://www.basketball-reference.com/teams/CHI', 'https://www.basketball-reference.com/teams/HOU', 'https://www.basketball-reference.com/teams/PHI', 'https://www.basketball-reference.com/teams/SEA', 'https://www.basketball-reference.com/teams/WSB', 'https://www.basketball-reference.com/teams/POR', 'https://www.basketball-reference.com/teams/NYA', 'https://www.basketball-reference.com/teams/KEN']
[INFO] Saved 20 rows to data/teams2.csv
https://www.basketball-reference.com/teams/NYK ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL', 'https://www.basketball-reference.com/teams/TOR', 'https://www.basketball-reference.com/teams/CLE', 'https://www.basketball-reference.com/teams/SAS', 'https://www.basketball-reference.com/teams/MIA', 'https://www.basketball-reference.com/teams/DAL', 'https://www.basketball-reference.com/teams/DET', 'https://www.basketball-reference.com/teams/CHI', 'https://www.basketball-reference.com/teams/HOU', 'https://www.basketball-reference.com/teams/PHI', 'https://www.basketball-reference.com/teams/SEA', 'https://www.basketball-reference.com/teams/WSB', 'https://www.basketball-reference.com/teams/POR', 'https://www.basketball-reference.com/teams/NYA', 'https://www.basketball-reference.com/teams/KEN', 'https://www.basketball-reference.com/teams/NYK']
[INFO] Saved 21 rows to data/teams2.csv
https://www.basketball-reference.com/teams/INA ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL', 'https://www.basketball-reference.com/teams/TOR', 'https://www.basketball-reference.com/teams/CLE', 'https://www.basketball-reference.com/teams/SAS', 'https://www.basketball-reference.com/teams/MIA', 'https://www.basketball-reference.com/teams/DAL', 'https://www.basketball-reference.com/teams/DET', 'https://www.basketball-reference.com/teams/CHI', 'https://www.basketball-reference.com/teams/HOU', 'https://www.basketball-reference.com/teams/PHI', 'https://www.basketball-reference.com/teams/SEA', 'https://www.basketball-reference.com/teams/WSB', 'https://www.basketball-reference.com/teams/POR', 'https://www.basketball-reference.com/teams/NYA', 'https://www.basketball-reference.com/teams/KEN', 'https://www.basketball-reference.com/teams/NYK', 'https://www.basketball-reference.com/teams/INA']
[INFO] Saved 22 rows to data/teams2.csv
https://www.basketball-reference.com/teams/UTS ['https://www.basketball-reference.com/teams/OKC', 'https://www.basketball-reference.com/teams/BOS', 'https://www.basketball-reference.com/teams/DEN', 'https://www.basketball-reference.com/teams/GSW', 'https://www.basketball-reference.com/teams/MIL', 'https://www.basketball-reference.com/teams/LAL', 'https://www.basketball-reference.com/teams/TOR', 'https://www.basketball-reference.com/teams/CLE', 'https://www.basketball-reference.com/teams/SAS', 'https://www.basketball-reference.com/teams/MIA', 'https://www.basketball-reference.com/teams/DAL', 'https://www.basketball-reference.com/teams/DET', 'https://www.basketball-reference.com/teams/CHI', 'https://www.basketball-reference.com/teams/HOU', 'https://www.basketball-reference.com/teams/PHI', 'https://www.basketball-reference.com/teams/SEA', 'https://www.basketball-reference.com/teams/WSB', 'https://www.basketball-reference.com/teams/POR', 'https://www.basketball-reference.com/teams/NYA', 'https://www.basketball-reference.com/teams/KEN', 'https://www.basketball-reference.com/teams/NYK', 'https://www.basketball-reference.com/teams/INA', 'https://www.basketball-reference.com/teams/UTS']
[INFO] Saved 23 rows to data/teams2.csv

[{'link': 'https://www.basketball-reference.com/teams/OKC',
  'team_full_name': 'Oklahoma City Thunder',
  'location': 'Oklahoma City, Oklahoma',
  'team_names': 'Oklahoma City Thunder, Seattle SuperSonics',
  'seasons': '59; 1967-68 to 2025-26',
  'seasons_count': 59,
  'seasons_range': '1967-68 to 2025-26',
  'record': '2538-2150, .541 W-L%',
  'playoff_appearances': 34,
  'championships': 2},
 {'link': 'https://www.basketball-reference.com/teams/BOS',
  'team_full_name': 'Boston Celtics',
  'location': 'Boston, Massachusetts',
  'team_names': 'Boston Celtics',
  'seasons': '80; 1946-47 to 2025-26',
  'seasons_count': 80,
  'seasons_range': '1946-47 to 2025-26',
  'record': '3695-2501, .596 W-L%',
  'playoff_appearances': 62,
  'championships': 18},
 {'link': 'https://www.basketball-reference.com/teams/DEN',
  'team_full_name': 'Denver Nuggets',
  'location': 'Denver, Colorado',
  'team_names': 'Denver Nuggets, Denver Rockets',
  'seasons': '59 (50 NBA & 9 ABA); 1967-68 to 2025-26',
  'seasons_count': None,
  'seasons_range': None,
  'record': '2417-2278, .515 W-L% (2004-1947 NBA & 413-331 ABA)',
  'playoff_appearances': '40 (31 NBA & 9 ABA)',
  'championships': '1 (1 NBA & 0 ABA)'},
 {'link': 'https://www.basketball-reference.com/teams/GSW',
  'team_full_name': 'Golden State Warriors',
  'location': 'San Francisco, California',
  'team_names': 'Golden State Warriors, San Francisco Warriors, Philadelphia Warriors',
  'seasons': '80; 1946-47 to 2025-26',
  'seasons_count': 80,
  'seasons_range': '1946-47 to 2025-26',
  'record': '3017-3168, .488 W-L%',
  'playoff_appearances': 38,
  'championships': 7},
 {'link': 'https://www.basketball-reference.com/teams/MIL',
  'team_full_name': 'Milwaukee Bucks',
  'location': 'Milwaukee, Wisconsin',
  'team_names': 'Milwaukee Bucks',
  'seasons': '58; 1968-69 to 2025-26',
  'seasons_count': 58,
  'seasons_range': '1968-69 to 2025-26',
  'record': '2437-2170, .529 W-L%',
  'playoff_appearances': 37,
  'championships': 2},
 {'link': 'https://www.basketball-reference.com/teams/LAL',
  'team_full_name': 'Los Angeles Lakers',
  'location': 'Los Angeles, California',
  'team_names': 'Los Angeles Lakers, Minneapolis Lakers',
  'seasons': '78; 1948-49 to 2025-26',
  'seasons_count': 78,
  'seasons_range': '1948-49 to 2025-26',
  'record': '3600-2486, .592 W-L%',
  'playoff_appearances': 65,
  'championships': 17},
 {'link': 'https://www.basketball-reference.com/teams/TOR',
  'team_full_name': 'Toronto Raptors',
  'location': 'Toronto, Canada',
  'team_names': 'Toronto Raptors',
  'seasons': '31; 1995-96 to 2025-26',
  'seasons_count': 31,
  'seasons_range': '1995-96 to 2025-26',
  'record': '1126-1266, .471 W-L%',
  'playoff_appearances': 13,
  'championships': 1},
 {'link': 'https://www.basketball-reference.com/teams/CLE',
  'team_full_name': 'Cleveland Cavaliers',
  'location': 'Cleveland, Ohio',
  'team_names': 'Cleveland Cavaliers',
  'seasons': '56; 1970-71 to 2025-26',
  'seasons_count': 56,
  'seasons_range': '1970-71 to 2025-26',
  'record': '2096-2339, .473 W-L%',
  'playoff_appearances': 25,
  'championships': 1},
 {'link': 'https://www.basketball-reference.com/teams/SAS',
  'team_full_name': 'San Antonio Spurs',
  'location': 'San Antonio, Texas',
  'team_names': 'San Antonio Spurs, Texas Chaparrals, Dallas Chaparrals',
  'seasons': '59 (50 NBA & 9 ABA); 1967-68 to 2025-26',
  'seasons_count': None,
  'seasons_range': None,
  'record': '2717-1976, .579 W-L% (2339-1610 NBA & 378-366 ABA)',
  'playoff_appearances': '47 (39 NBA & 8 ABA)',
  'championships': '5 (5 NBA & 0 ABA)'},
 {'link': 'https://www.basketball-reference.com/teams/MIA',
  'team_full_name': 'Miami Heat',
  'location': 'Miami, Florida',
  'team_names': 'Miami Heat',
  'seasons': '38; 1988-89 to 2025-26',
  'seasons_count': 38,
  'seasons_range': '1988-89 to 2025-26',
  'record': '1558-1409, .525 W-L%',
  'playoff_appearances': 26,
  'championships': 3},
 {'link': 'https://www.basketball-reference.com/teams/DAL',
  'team_full_name': 'Dallas Mavericks',
  'location': 'Dallas, Texas',
  'team_names': 'Dallas Mavericks',
  'seasons': '46; 1980-81 to 2025-26',
  'seasons_count': 46,
  'seasons_range': '1980-81 to 2025-26',
  'record': '1836-1789, .506 W-L%',
  'playoff_appearances': 25,
  'championships': 1},
 {'link': 'https://www.basketball-reference.com/teams/DET',
  'team_full_name': 'Detroit Pistons',
  'location': 'Detroit, Michigan',
  'team_names': 'Detroit Pistons, Fort Wayne Pistons',
  'seasons': '78; 1948-49 to 2025-26',
  'seasons_count': 78,
  'seasons_range': '1948-49 to 2025-26',
  'record': '2871-3209, .472 W-L%',
  'playoff_appearances': 43,
  'championships': 3},
 {'link': 'https://www.basketball-reference.com/teams/CHI',
  'team_full_name': 'Chicago Bulls',
  'location': 'Chicago, Illinois',
  'team_names': 'Chicago Bulls',
  'seasons': '60; 1966-67 to 2025-26',
  'seasons_count': 60,
  'seasons_range': '1966-67 to 2025-26',
  'record': '2422-2340, .509 W-L%',
  'playoff_appearances': 36,
  'championships': 6},
 {'link': 'https://www.basketball-reference.com/teams/HOU',
  'team_full_name': 'Houston Rockets',
  'location': 'Houston, Texas',
  'team_names': 'Houston Rockets, San Diego Rockets',
  'seasons': '59; 1967-68 to 2025-26',
  'seasons_count': 59,
  'seasons_range': '1967-68 to 2025-26',
  'record': '2421-2267, .516 W-L%',
  'playoff_appearances': 35,
  'championships': 2},
 {'link': 'https://www.basketball-reference.com/teams/PHI',
  'team_full_name': 'Philadelphia 76ers',
  'location': 'Philadelphia, Pennsylvania',
  'team_names': 'Philadelphia 76ers, Syracuse Nationals',
  'seasons': '77; 1949-50 to 2025-26',
  'seasons_count': 77,
  'seasons_range': '1949-50 to 2025-26',
  'record': '3125-2898, .519 W-L%',
  'playoff_appearances': 54,
  'championships': 3},
 {'link': 'https://www.basketball-reference.com/teams/SEA',
  'team_full_name': 'Oklahoma City Thunder',
  'location': 'Oklahoma City, Oklahoma',
  'team_names': 'Oklahoma City Thunder, Seattle SuperSonics',
  'seasons': '59; 1967-68 to 2025-26',
  'seasons_count': 59,
  'seasons_range': '1967-68 to 2025-26',
  'record': '2538-2150, .541 W-L%',
  'playoff_appearances': 34,
  'championships': 2},
 {'link': 'https://www.basketball-reference.com/teams/WSB',
  'team_full_name': 'Washington Wizards',
  'location': 'Washington, District of Columbia',
  'team_names': 'Washington Wizards, Washington Bullets, Capital Bullets, Baltimore Bullets, Chicago Zephyrs, Chicago Packers',
  'seasons': '65; 1961-62 to 2025-26',
  'seasons_count': 65,
  'seasons_range': '1961-62 to 2025-26',
  'record': '2290-2879, .443 W-L%',
  'playoff_appearances': 30,
  'championships': 1},
 {'link': 'https://www.basketball-reference.com/teams/POR',
  'team_full_name': 'Portland Trail Blazers',
  'location': 'Portland, Oregon',
  'team_names': 'Portland Trail Blazers',
  'seasons': '56; 1970-71 to 2025-26',
  'seasons_count': 56,
  'seasons_range': '1970-71 to 2025-26',
  'record': '2328-2116, .524 W-L%',
  'playoff_appearances': 37,
  'championships': 1},
 {'link': 'https://www.basketball-reference.com/teams/NYA',
  'team_full_name': 'Brooklyn Nets',
  'location': 'Brooklyn, New York',
  'team_names': 'Brooklyn Nets, New Jersey Nets, New York Nets, New Jersey Americans',
  'seasons': '59 (50 NBA & 9 ABA); 1967-68 to 2025-26',
  'seasons_count': None,
  'seasons_range': None,
  'record': '2054-2640, .438 W-L% (1680-2270 NBA & 374-370 ABA)',
  'playoff_appearances': '31 (24 NBA & 7 ABA)',
  'championships': '2 (0 NBA & 2 ABA)'},
 {'link': 'https://www.basketball-reference.com/teams/KEN',
  'team_full_name': 'Kentucky Colonels',
  'location': 'Louisville, Kentucky',
  'team_names': 'Kentucky Colonels',
  'seasons': '9; 1967-68 to 1975-76',
  'seasons_count': 9,
  'seasons_range': '1967-68 to 1975-76',
  'record': '448-296, .602 W-L%',
  'playoff_appearances': 9,
  'championships': 1},
 {'link': 'https://www.basketball-reference.com/teams/NYK',
  'team_full_name': 'New York Knicks',
  'location': 'New York, New York',
  'team_names': 'New York Knicks',
  'seasons': '80; 1946-47 to 2025-26',
  'seasons_count': 80,
  'seasons_range': '1946-47 to 2025-26',
  'record': '3025-3162, .489 W-L%',
  'playoff_appearances': 46,
  'championships': 2},
 {'link': 'https://www.basketball-reference.com/teams/INA',
  'team_full_name': 'Indiana Pacers',
  'location': 'Indianapolis, Indiana',
  'team_names': 'Indiana Pacers',
  'seasons': '59 (50 NBA & 9 ABA); 1967-68 to 2025-26',
  'seasons_count': None,
  'seasons_range': None,
  'record': '2407-2287, .513 W-L% (1980-1970 NBA & 427-317 ABA)',
  'playoff_appearances': '38 (29 NBA & 9 ABA)',
  'championships': '3 (0 NBA & 3 ABA)'},
 {'link': 'https://www.basketball-reference.com/teams/UTS',
  'team_full_name': 'Utah Stars',
  'location': 'Salt Lake City, Utah',
  'team_names': 'Utah Stars, Los Angeles Stars, Anaheim Amigos',
  'seasons': '9; 1967-68 to 1975-76',
  'seasons_count': 9,
  'seasons_range': '1967-68 to 1975-76',
  'record': '366-310, .541 W-L%',
  'playoff_appearances': 6,
  'championships': 1},
 {'link': 'https://www.basketball-reference.com/teams/OAK',
  'team_full_name': 'Virginia Squires',
  'location': 'Norfolk, Virginia',
  'team_names': 'Virginia Squires, Washington Capitols, Oakland Oaks',
  'seasons': '9; 1967-68 to 1975-76',
  'seasons_count': 9,
  'seasons_range': '1967-68 to 1975-76',
  'record': '326-417, .439 W-L%',
  'playoff_appearances': 6,
  'championships': 1},
 {'link': 'https://www.basketball-reference.com/teams/PTP',
  'team_full_name': 'Pittsburgh Condors',
  'location': 'Pittsburgh, Pennsylvania',
  'team_names': 'Pittsburgh Condors, Minnesota Pipers, Pittsburgh Pipers',
  'seasons': '5; 1967-68 to 1971-72',
  'seasons_count': 5,
  'seasons_range': '1967-68 to 1971-72',
  'record': '180-228, .441 W-L%',
  'playoff_appearances': 2,
  'championships': 1},
 {'link': 'https://www.basketball-reference.com/teams/STL',
  'team_full_name': 'Atlanta Hawks',
  'location': 'Atlanta, Georgia',
  'team_names': 'Atlanta Hawks, St. Louis Hawks, Milwaukee Hawks, Tri-Cities Blackhawks',
  'seasons': '77; 1949-50 to 2025-26',
  'seasons_count': 77,
  'seasons_range': '1949-50 to 2025-26',
  'record': '2967-3052, .493 W-L%',
  'playoff_appearances': 49,
  'championships': 1},
 {'link': 'https://www.basketball-reference.com/teams/PHW',
  'team_full_name': 'Golden State Warriors',
  'location': 'San Francisco, California',
  'team_names': 'Golden State Warriors, San Francisco Warriors, Philadelphia Warriors',
  'seasons': '80; 1946-47 to 2025-26',
  'seasons_count': 80,
  'seasons_range': '1946-47 to 2025-26',
  'record': '3017-3168, .488 W-L%',
  'playoff_appearances': 38,
  'championships': 7},
 {'link': 'https://www.basketball-reference.com/teams/SYR',
  'team_full_name': 'Philadelphia 76ers',
  'location': 'Philadelphia, Pennsylvania',
  'team_names': 'Philadelphia 76ers, Syracuse Nationals',
  'seasons': '77; 1949-50 to 2025-26',
  'seasons_count': 77,
  'seasons_range': '1949-50 to 2025-26',
  'record': '3125-2898, .519 W-L%',
  'playoff_appearances': 54,
  'championships': 3},
 {'link': 'https://www.basketball-reference.com/teams/MNL',
  'team_full_name': 'Los Angeles Lakers',
  'location': 'Los Angeles, California',
  'team_names': 'Los Angeles Lakers, Minneapolis Lakers',
  'seasons': '78; 1948-49 to 2025-26',
  'seasons_count': 78,
  'seasons_range': '1948-49 to 2025-26',
  'record': '3600-2486, .592 W-L%',
  'playoff_appearances': 65,
  'championships': 17},
 {'link': 'https://www.basketball-reference.com/teams/ROC',
  'team_full_name': 'Sacramento Kings',
  'location': 'Sacramento, California',
  'team_names': 'Sacramento Kings, Kansas City Kings, Kansas City-Omaha Kings, Cincinnati Royals, Rochester Royals',
  'seasons': '78; 1948-49 to 2025-26',
  'seasons_count': 78,
  'seasons_range': '1948-49 to 2025-26',
  'record': '2788-3299, .458 W-L%',
  'playoff_appearances': 30,
  'championships': 1},
 {'link': 'https://www.basketball-reference.com/teams/BLB',
  'team_full_name': 'Baltimore Bullets',
  'location': 'Baltimore, Maryland',
  'team_names': 'Baltimore Bullets',
  'seasons': '8; 1947-48 to 1954-55',
  'seasons_count': 8,
  'seasons_range': '1947-48 to 1954-55',
  'record': '158-292, .351 W-L%',
  'playoff_appearances': 3,
  'championships': 1},
 {'link': 'https://www.basketball-reference.com/teams/BRK',
  'team_full_name': 'Brooklyn Nets',
  'location': 'Brooklyn, New York',
  'team_names': 'Brooklyn Nets, New Jersey Nets, New York Nets, New Jersey Americans',
  'seasons': '59 (50 NBA & 9 ABA); 1967-68 to 2025-26',
  'seasons_count': None,
  'seasons_range': None,
  'record': '2054-2640, .438 W-L% (1680-2270 NBA & 374-370 ABA)',
  'playoff_appearances': '31 (24 NBA & 7 ABA)',
  'championships': '2 (0 NBA & 2 ABA)'},
 {'link': 'https://www.basketball-reference.com/teams/IND',
  'team_full_name': 'Indiana Pacers',
  'location': 'Indianapolis, Indiana',
  'team_names': 'Indiana Pacers',
  'seasons': '59 (50 NBA & 9 ABA); 1967-68 to 2025-26',
  'seasons_count': None,
  'seasons_range': None,
  'record': '2407-2287, .513 W-L% (1980-1970 NBA & 427-317 ABA)',
  'playoff_appearances': '38 (29 NBA & 9 ABA)',
  'championships': '3 (0 NBA & 3 ABA)'},
 {'link': 'https://www.basketball-reference.com/teams/ATL',
  'team_full_name': 'Atlanta Hawks',
  'location': 'Atlanta, Georgia',
  'team_names': 'Atlanta Hawks, St. Louis Hawks, Milwaukee Hawks, Tri-Cities Blackhawks',
  'seasons': '77; 1949-50 to 2025-26',
  'seasons_count': 77,
  'seasons_range': '1949-50 to 2025-26',
  'record': '2967-3052, .493 W-L%',
  'playoff_appearances': 49,
  'championships': 1},
 {'link': 'https://www.basketball-reference.com/teams/CHO',
  'team_full_name': 'Charlotte Hornets',
  'location': 'Charlotte, North Carolina',
  'team_names': 'Charlotte Bobcats, Charlotte Hornets',
  'seasons': '36; 1988-89 to 2025-26',
  'seasons_count': 36,
  'seasons_range': '1988-89 to 2025-26',
  'record': '1193-1602, .427 W-L%',
  'playoff_appearances': 10,
  'championships': 0},
 {'link': 'https://www.basketball-reference.com/teams/WAS',
  'team_full_name': 'Washington Wizards',
  'location': 'Washington, District of Columbia',
  'team_names': 'Washington Wizards, Washington Bullets, Capital Bullets, Baltimore Bullets, Chicago Zephyrs, Chicago Packers',
  'seasons': '65; 1961-62 to 2025-26',
  'seasons_count': 65,
  'seasons_range': '1961-62 to 2025-26',
  'record': '2290-2879, .443 W-L%',
  'playoff_appearances': 30,
  'championships': 1},
 {'link': 'https://www.basketball-reference.com/teams/ORL',
  'team_full_name': 'Orlando Magic',
  'location': 'Orlando, Florida',
  'team_names': 'Orlando Magic',
  'seasons': '37; 1989-90 to 2025-26',
  'seasons_count': 37,
  'seasons_range': '1989-90 to 2025-26',
  'record': '1356-1529, .470 W-L%',
  'playoff_appearances': 18,
  'championships': 0},
 {'link': 'https://www.basketball-reference.com/teams/UTA',
  'team_full_name': 'Utah Jazz',
  'location': 'Salt Lake City, Utah',
  'team_names': 'Utah Jazz, New Orleans Jazz',
  'seasons': '52; 1974-75 to 2025-26',
  'seasons_count': 52,
  'seasons_range': '1974-75 to 2025-26',
  'record': '2194-1920, .533 W-L%',
  'playoff_appearances': 31,
  'championships': 0},
 {'link': 'https://www.basketball-reference.com/teams/MIN',
  'team_full_name': 'Minnesota Timberwolves',
  'location': 'Minneapolis, Minnesota',
  'team_names': 'Minnesota Timberwolves',
  'seasons': '37; 1989-90 to 2025-26',
  'seasons_count': 37,
  'seasons_range': '1989-90 to 2025-26',
  'record': '1196-1680, .416 W-L%',
  'playoff_appearances': 13,
  'championships': 0},
 {'link': 'https://www.basketball-reference.com/teams/LAC',
  'team_full_name': 'Los Angeles Clippers',
  'location': 'Los Angeles, California',
  'team_names': 'Los Angeles Clippers, San Diego Clippers, Buffalo Braves',
  'seasons': '56; 1970-71 to 2025-26',
  'seasons_count': 56,
  'seasons_range': '1970-71 to 2025-26',
  'record': '1893-2549, .426 W-L%',
  'playoff_appearances': 19,
  'championships': 0},
 {'link': 'https://www.basketball-reference.com/teams/SAC',
  'team_full_name': 'Sacramento Kings',
  'location': 'Sacramento, California',
  'team_names': 'Sacramento Kings, Kansas City Kings, Kansas City-Omaha Kings, Cincinnati Royals, Rochester Royals',
  'seasons': '78; 1948-49 to 2025-26',
  'seasons_count': 78,
  'seasons_range': '1948-49 to 2025-26',
  'record': '2788-3299, .458 W-L%',
  'playoff_appearances': 30,
  'championships': 1},
 {'link': 'https://www.basketball-reference.com/teams/PHO',
  'team_full_name': 'Phoenix Suns',
  'location': 'Phoenix, Arizona',
  'team_names': 'Phoenix Suns',
  'seasons': '58; 1968-69 to 2025-26',
  'seasons_count': 58,
  'seasons_range': '1968-69 to 2025-26',
  'record': '2465-2142, .535 W-L%',
  'playoff_appearances': 33,
  'championships': 0},
 {'link': 'https://www.basketball-reference.com/teams/MEM',
  'team_full_name': 'Memphis Grizzlies',
  'location': 'Memphis, Tennessee',
  'team_names': 'Memphis Grizzlies, Vancouver Grizzlies',
  'seasons': '31; 1995-96 to 2025-26',
  'seasons_count': 31,
  'seasons_range': '1995-96 to 2025-26',
  'record': '1046-1347, .437 W-L%',
  'playoff_appearances': 14,
  'championships': 0},
 {'link': 'https://www.basketball-reference.com/teams/NOP',
  'team_full_name': 'New Orleans Pelicans',
  'location': 'New Orleans, Louisiana',
  'team_names': 'New Orleans Pelicans, New Orleans/Oklahoma City Hornets, New Orleans Hornets',
  'seasons': '24; 2002-03 to 2025-26',
  'seasons_count': 24,
  'seasons_range': '2002-03 to 2025-26',
  'record': '852-998, .461 W-L%',
  'playoff_appearances': 9,
  'championships': 0}]

In [109]:
seen = []

def GetTeamSeasonsDetail (team):
    session = requests.Session()
    session.headers.update({
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                    "(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36",
        "Accept-Language": "en-US,en;q=0.9"
    })


    url =team['Link']
    
    href = url
    if href in seen:
        return None
    
    html = fetch_page(href, session,way=1)
    if html is None:
        return {
            "link":href
        }

    
    soup = BeautifulSoup(html , 'html.parser')
    seen.append(href)
    meta = None
    meta = soup.select_one("#info > #meta")
    result = {"link":href}
    if meta is None:
        return {"link":href}
    
    title_span = meta.select('h1 > span') 
    result["team_full_name"] =   title_span[1].get_text(strip=True) if title_span[1] else None 
    result["season"] =   title_span[0].get_text(strip=True) if title_span[0] else None 

    
    for p in meta.select("p"):
        strong = p.find("strong")
        if not strong:
            continue
        
        label = strong.get_text(strip=True).rstrip(":")
        key = _to_snake(label)  
         
        if '_playoffs' in key:
            continue

        parts = []
        for sib in strong.next_siblings:
            if isinstance(sib, NavigableString):
                txt = str(sib)
            else:
                txt = sib.get_text(separator=" ", strip=True)
            if txt and txt != "\n":
                parts.append(txt)
        raw_value = " ".join(parts)
        value = re.sub(r"\s+", " ", raw_value).strip()
        value = value.strip(" ;:\n\t,")

        coerced = _try_int(value)
        
        result[key] = coerced


    
   
    return result
    
teams_filterd = [d for d in teams if d.get("TeamName") != "F" and d.get("TeamName") != "Teams"]

team_seasons_details = []

counter = 0
for team in teams_filterd:
    res = GetTeamSeasonsDetail(team)
    if(res != None):
        team_seasons_details.append(res)
        save_results_csv(team_seasons_details,[
                "link",
                "team_full_name",
                "season",
                'record',
                'coach',
                'executive',
                "pts_g",
                'srs',
                'off_rtg',
                'expected_w_l',
                'preseason_odds',
                'playoff_appearances',
                'arena'
            ],'data/teams_seasons.csv')
    counter = counter+1

[INFO] Saved 1 rows to data/teams_seasons.csv
[INFO] Saved 2 rows to data/teams_seasons.csv
[INFO] Saved 3 rows to data/teams_seasons.csv
[INFO] Saved 4 rows to data/teams_seasons.csv
[INFO] Saved 5 rows to data/teams_seasons.csv
[INFO] Saved 6 rows to data/teams_seasons.csv
[INFO] Saved 7 rows to data/teams_seasons.csv
[INFO] Saved 8 rows to data/teams_seasons.csv
[INFO] Saved 9 rows to data/teams_seasons.csv
[INFO] Saved 10 rows to data/teams_seasons.csv
[INFO] Saved 11 rows to data/teams_seasons.csv
[INFO] Saved 12 rows to data/teams_seasons.csv
[INFO] Saved 13 rows to data/teams_seasons.csv
[INFO] Saved 14 rows to data/teams_seasons.csv
[INFO] Saved 15 rows to data/teams_seasons.csv
[INFO] Saved 16 rows to data/teams_seasons.csv
[INFO] Saved 17 rows to data/teams_seasons.csv
[INFO] Saved 18 rows to data/teams_seasons.csv
[INFO] Saved 19 rows to data/teams_seasons.csv
[INFO] Saved 20 rows to data/teams_seasons.csv
[INFO] Saved 21 rows to data/teams_seasons.csv
[INFO] Saved 22 rows to data/teams_seasons.csv
[INFO] Saved 23 rows to data/teams_seasons.csv
[INFO] Saved 24 rows to data/teams_seasons.csv
[INFO] Saved 25 rows to data/teams_seasons.csv
[INFO] Saved 26 rows to data/teams_seasons.csv
[INFO] Saved 27 rows to data/teams_seasons.csv
[INFO] Saved 28 rows to data/teams_seasons.csv
[INFO] Saved 29 rows to data/teams_seasons.csv
[INFO] Saved 30 rows to data/teams_seasons.csv
[INFO] Saved 31 rows to data/teams_seasons.csv
[INFO] Saved 32 rows to data/teams_seasons.csv
[INFO] Saved 33 rows to data/teams_seasons.csv
[INFO] Saved 34 rows to data/teams_seasons.csv
[INFO] Saved 35 rows to data/teams_seasons.csv
[INFO] Saved 36 rows to data/teams_seasons.csv
[INFO] Saved 37 rows to data/teams_seasons.csv
[INFO] Saved 38 rows to data/teams_seasons.csv
[INFO] Saved 39 rows to data/teams_seasons.csv
[INFO] Saved 40 rows to data/teams_seasons.csv
[INFO] Saved 41 rows to data/teams_seasons.csv
[INFO] Saved 42 rows to data/teams_seasons.csv
[INFO] Saved 43 rows to data/teams_seasons.csv
[INFO] Saved 44 rows to data/teams_seasons.csv
[INFO] Saved 45 rows to data/teams_seasons.csv
[INFO] Saved 46 rows to data/teams_seasons.csv
[INFO] Saved 47 rows to data/teams_seasons.csv
[INFO] Saved 48 rows to data/teams_seasons.csv
[INFO] Saved 49 rows to data/teams_seasons.csv
[INFO] Saved 50 rows to data/teams_seasons.csv
[INFO] Saved 51 rows to data/teams_seasons.csv
[INFO] Saved 52 rows to data/teams_seasons.csv
[INFO] Saved 53 rows to data/teams_seasons.csv
[INFO] Saved 54 rows to data/teams_seasons.csv
[INFO] Saved 55 rows to data/teams_seasons.csv
[INFO] Saved 56 rows to data/teams_seasons.csv
[INFO] Saved 57 rows to data/teams_seasons.csv
[INFO] Saved 58 rows to data/teams_seasons.csv
[INFO] Saved 59 rows to data/teams_seasons.csv
[INFO] Saved 60 rows to data/teams_seasons.csv
[INFO] Saved 61 rows to data/teams_seasons.csv
[INFO] Saved 62 rows to data/teams_seasons.csv
[INFO] Saved 63 rows to data/teams_seasons.csv
[INFO] Saved 64 rows to data/teams_seasons.csv
[INFO] Saved 65 rows to data/teams_seasons.csv
[INFO] Saved 66 rows to data/teams_seasons.csv
[INFO] Saved 67 rows to data/teams_seasons.csv
[INFO] Saved 68 rows to data/teams_seasons.csv
[INFO] Saved 69 rows to data/teams_seasons.csv
[INFO] Saved 70 rows to data/teams_seasons.csv
[INFO] Saved 71 rows to data/teams_seasons.csv
[INFO] Saved 72 rows to data/teams_seasons.csv
[INFO] Saved 73 rows to data/teams_seasons.csv
[INFO] Saved 74 rows to data/teams_seasons.csv
[INFO] Saved 75 rows to data/teams_seasons.csv
[INFO] Saved 76 rows to data/teams_seasons.csv
[INFO] Saved 77 rows to data/teams_seasons.csv
[INFO] Saved 78 rows to data/teams_seasons.csv
[INFO] Saved 79 rows to data/teams_seasons.csv
[INFO] Saved 80 rows to data/teams_seasons.csv
[INFO] Saved 81 rows to data/teams_seasons.csv
[INFO] Saved 82 rows to data/teams_seasons.csv
[INFO] Saved 83 rows to data/teams_seasons.csv
[INFO] Saved 84 rows to data/teams_seasons.csv
[INFO] Saved 85 rows to data/teams_seasons.csv
[INFO] Saved 86 rows to data/teams_seasons.csv
[INFO] Saved 87 rows to data/teams_seasons.csv
[INFO] Saved 88 rows to data/teams_seasons.csv
[INFO] Saved 89 rows to data/teams_seasons.csv
[INFO] Saved 90 rows to data/teams_seasons.csv
[INFO] Saved 91 rows to data/teams_seasons.csv
[INFO] Saved 92 rows to data/teams_seasons.csv
[INFO] Saved 93 rows to data/teams_seasons.csv
[INFO] Saved 94 rows to data/teams_seasons.csv
[INFO] Saved 95 rows to data/teams_seasons.csv
[INFO] Saved 96 rows to data/teams_seasons.csv
[INFO] Saved 97 rows to data/teams_seasons.csv
[INFO] Saved 98 rows to data/teams_seasons.csv
[INFO] Saved 99 rows to data/teams_seasons.csv
[INFO] Saved 100 rows to data/teams_seasons.csv
[INFO] Saved 101 rows to data/teams_seasons.csv
[INFO] Saved 102 rows to data/teams_seasons.csv
[INFO] Saved 103 rows to data/teams_seasons.csv
[INFO] Saved 104 rows to data/teams_seasons.csv
[INFO] Saved 105 rows to data/teams_seasons.csv
[INFO] Saved 106 rows to data/teams_seasons.csv
[INFO] Saved 107 rows to data/teams_seasons.csv
[INFO] Saved 108 rows to data/teams_seasons.csv
[INFO] Saved 109 rows to data/teams_seasons.csv
[INFO] Saved 110 rows to data/teams_seasons.csv
[INFO] Saved 111 rows to data/teams_seasons.csv
[INFO] Saved 112 rows to data/teams_seasons.csv
[INFO] Saved 113 rows to data/teams_seasons.csv
[INFO] Saved 114 rows to data/teams_seasons.csv
[INFO] Saved 115 rows to data/teams_seasons.csv
[INFO] Saved 116 rows to data/teams_seasons.csv
[INFO] Saved 117 rows to data/teams_seasons.csv
[INFO] Saved 118 rows to data/teams_seasons.csv
[INFO] Saved 119 rows to data/teams_seasons.csv

In [108]:
team_details_df=pd.DataFrame(team_details)

Utilies.make_df_pretty(team_details_df)


team_details_df

,link,team_full_name,location,team_names,seasons,seasons_count,seasons_range,record,playoff_appearances,championships
0,https://www.basketball-reference.com/teams/OKC,Oklahoma City Thunder,"Oklahoma City, Oklahoma","Oklahoma City Thunder, Seattle SuperSonics",59; 1967-68 to 2025-26,59.0,1967-68 to 2025-26,"2538-2150, .541 W-L%",34,2
1,https://www.basketball-reference.com/teams/BOS,Boston Celtics,"Boston, Massachusetts",Boston Celtics,80; 1946-47 to 2025-26,80.0,1946-47 to 2025-26,"3695-2501, .596 W-L%",62,18
2,https://www.basketball-reference.com/teams/DEN,Denver Nuggets,"Denver, Colorado","Denver Nuggets, Denver Rockets",59 (50 NBA & 9 ABA); 1967-68 to 2025-26,NaN,None,"2417-2278, .515 W-L% (2004-1947 NBA & 413-331 ...",40 (31 NBA & 9 ABA),1 (1 NBA & 0 ABA)
3,https://www.basketball-reference.com/teams/GSW,Golden State Warriors,"San Francisco, California","Golden State Warriors, San Francisco Warriors,...",80; 1946-47 to 2025-26,80.0,1946-47 to 2025-26,"3017-3168, .488 W-L%",38,7
4,https://www.basketball-reference.com/teams/MIL,Milwaukee Bucks,"Milwaukee, Wisconsin",Milwaukee Bucks,58; 1968-69 to 2025-26,58.0,1968-69 to 2025-26,"2437-2170, .529 W-L%",37,2
5,https://www.basketball-reference.com/teams/LAL,Los Angeles Lakers,"Los Angeles, California","Los Angeles Lakers, Minneapolis Lakers",78; 1948-49 to 2025-26,78.0,1948-49 to 2025-26,"3600-2486, .592 W-L%",65,17
6,https://www.basketball-reference.com/teams/TOR,Toronto Raptors,"Toronto, Canada",Toronto Raptors,31; 1995-96 to 2025-26,31.0,1995-96 to 2025-26,"1126-1266, .471 W-L%",13,1
7,https://www.basketball-reference.com/teams/CLE,Cleveland Cavaliers,"Cleveland, Ohio",Cleveland Cavaliers,56; 1970-71 to 2025-26,56.0,1970-71 to 2025-26,"2096-2339, .473 W-L%",25,1
8,https://www.basketball-reference.com/teams/SAS,San Antonio Spurs,"San Antonio, Texas","San Antonio Spurs, Texas Chaparrals, Dallas Ch...",59 (50 NBA & 9 ABA); 1967-68 to 2025-26,NaN,None,"2717-1976, .579 W-L% (2339-1610 NBA & 378-366 ...",47 (39 NBA & 8 ABA),5 (5 NBA & 0 ABA)
9,https://www.basketball-reference.com/teams/MIA,Miami Heat,"Miami, Florida",Miami Heat,38; 1988-89 to 2025-26,38.0,1988-89 to 2025-26,"1558-1409, .525 W-L%",26,3
10,https://www.basketball-reference.com/teams/DAL,Dallas Mavericks,"Dallas, Texas",Dallas Mavericks,46; 1980-81 to 2025-26,46.0,1980-81 to 2025-26,"1836-1789, .506 W-L%",25,1
11,https://www.basketball-reference.com/teams/DET,Detroit Pistons,"Detroit, Michigan","Detroit Pistons, Fort Wayne Pistons",78; 1948-49 to 2025-26,78.0,1948-49 to 2025-26,"2871-3209, .472 W-L%",43,3
12,https://www.basketball-reference.com/teams/CHI,Chicago Bulls,"Chicago, Illinois",Chicago Bulls,60; 1966-67 to 2025-26,60.0,1966-67 to 2025-26,"2422-2340, .509 W-L%",36,6
13,https://www.basketball-reference.com/teams/HOU,Houston Rockets,"Houston, Texas","Houston Rockets, San Diego Rockets",59; 1967-68 to 2025-26,59.0,1967-68 to 2025-26,"2421-2267, .516 W-L%",35,2
14,https://www.basketball-reference.com/teams/PHI,Philadelphia 76ers,"Philadelphia, Pennsylvania","Philadelphia 76ers, Syracuse Nationals",77; 1949-50 to 2025-26,77.0,1949-50 to 2025-26,"3125-2898, .519 W-L%",54,3
15,https://www.basketball-reference.com/teams/SEA,Oklahoma City Thunder,"Oklahoma City, Oklahoma","Oklahoma City Thunder, Seattle SuperSonics",59; 1967-68 to 2025-26,59.0,1967-68 to 2025-26,"2538-2150, .541 W-L%",34,2
16,https://www.basketball-reference.com/teams/WSB,Washington Wizards,"Washington, District of Columbia","Washington Wizards, Washington Bullets, Capita...",65; 1961-62 to 2025-26,65.0,1961-62 to 2025-26,"2290-2879, .443 W-L%",30,1
17,https://www.basketball-reference.com/teams/POR,Portland Trail Blazers,"Portland, Oregon",Portland Trail Blazers,56; 1970-71 to 2025-26,56.0,1970-71 to 2025-26,"2328-2116, .524 W-L%",37,1
18,https://www.basketball-reference.com/teams/NYA,Brooklyn Nets,"Brooklyn, New York","Brooklyn Nets, New Jersey Nets, New York Nets,...",59 (50 NBA & 9 ABA); 1967-68 to 2025-26,NaN,None,"2054-2640, .438 W-L% (1680-2270 NBA & 374-370 ...",31 (24 NBA & 7 ABA),2 (0 NBA & 2 ABA)
19,https://www.basketball-reference.com/teams/KEN,Kentucky Colonels,"Louisville, Kentucky",Kentucky Colonels,9; 1967-68 to 1975-76,9.0,1967-68 to 1975-76,"448-296, .602 W-L%",9,1
20,https://www.basketball-reference.com/teams/NYK,New York Knicks,"New York, New York",New York Knicks,80; 1946-47 to 2025-26,80.0,1946-47 to 2025-26,"3025-3162, .489 W-L%",46,2
21,https://www.basketball-reference.com/teams/INA,Indiana Pacers,"Indianapolis, Indiana",Indiana Pacers,59 (50 NBA & 9 ABA); 1967-68 to 2025-26,NaN,None,"2407-2287, .513 W-L% (1980-1970 NBA & 427-317 ...",38 (29 NBA & 9 ABA),3 (0 NBA & 3 ABA)
22,https://www.basketball-reference.com/teams/UTS,Utah Stars,"Salt Lake City, Utah","Utah Stars, Los Angeles Stars, Anaheim Amigos",9; 1967-68 to 1975-76,9.0,1967-68 to 1975-76,"366-310, .541 W-L%",6,1
23,https://www.basketball-reference.com/teams/OAK,Virginia Squires,"Norfolk, Virginia","Virginia Squires, Washington Capitols, Oakland...",9; 1967-68 to 1975-76,9.0,1967-68 to 1975-76,"326-417, .439 W-L%",6,1
24,https://www.basketball-reference.com/teams/PTP,Pittsburgh Condors,"Pittsburgh, Pennsylvania","Pittsburgh Condors, Minnesota Pipers, Pittsbur...",5; 1967-68 to 1971-72,5.0,1967-68 to 1971-72,"180-228, .441 W-L%",2,1
25,https://www.basketball-reference.com/teams/STL,Atlanta Hawks,"Atlanta, Georgia","Atlanta Hawks, St. Louis Hawks, Milwaukee Hawk...",77; 1949-50 to 2025-26,77.0,1949-50 to 2025-26,"2967-3052, .493 W-L%",49,1
26,https://www.basketball-reference.com/teams/PHW,Golden State Warriors,"San Francisco, California","Golden State Warriors, San Francisco Warriors,...",80; 1946-47 to 2025-26,80.0,1946-47 to 2025-26,"3017-3168, .488 W-L%",38,7
27,https://www.basketball-reference.com/teams/SYR,Philadelphia 76ers,"Philadelphia, Pennsylvania","Philadelphia 76ers, Syracuse Nationals",77; 1949-50 to 2025-26,77.0,1949-50 to 2025-26,"3125-2898, .519 W-L%",54,3
28,https://www.basketball-reference.com/teams/MNL,Los Angeles Lakers,"Los Angeles, California","Los Angeles Lakers, Minneapolis Lakers",78; 1948-49 to 2025-26,78.0,1948-49 to 2025-26,"3600-2486, .592 W-L%",65,17
29,https://www.basketball-reference.com/teams/ROC,Sacramento Kings,"Sacramento, California","Sacramento Kings, Kansas City Kings, Kansas Ci...",78; 1948-49 to 2025-26,78.0,1948-49 to 2025-26,"2788-3299, .458 W-L%",30,1
30,https://www.basketball-reference.com/teams/BLB,Baltimore Bullets,"Baltimore, Maryland",Baltimore Bullets,8; 1947-48 to 1954-55,8.0,1947-48 to 1954-55,"158-292, .351 W-L%",3,1
31,https://www.basketball-reference.com/teams/BRK,Brooklyn Nets,"Brooklyn, New York","Brooklyn Nets, New Jersey Nets, New York Nets,...",59 (50 NBA & 9 ABA); 1967-68 to 2025-26,NaN,None,"2054-2640, .438 W-L% (1680-2270 NBA & 374-370 ...",31 (24 NBA & 7 ABA),2 (0 NBA & 2 ABA)
32,https://www.basketball-reference.com/teams/IND,Indiana Pacers,"Indianapolis, Indiana",Indiana Pacers,59 (50 NBA & 9 ABA); 1967-68 to 2025-26,NaN,None,"2407-2287, .513 W-L% (1980-1970 NBA & 427-317 ...",38 (29 NBA & 9 ABA),3 (0 NBA & 3 ABA)
33,https://www.basketball-reference.com/teams/ATL,Atlanta Hawks,"Atlanta, Georgia","Atlanta Hawks, St. Louis Hawks, Milwaukee Hawk...",77; 1949-50 to 2025-26,77.0,1949-50 to 2025-26,"2967-3052, .493 W-L%",49,1
34,https://www.basketball-reference.com/teams/CHO,Charlotte Hornets,"Charlotte, North Carolina","Charlotte Bobcats, Charlotte Hornets",36; 1988-89 to 2025-26,36.0,1988-89 to 2025-26,"1193-1602, .427 W-L%",10,0
35,https://www.basketball-reference.com/teams/WAS,Washington Wizards,"Washington, District of Columbia","Washington Wizards, Washington Bullets, Capita...",65; 1961-62 to 2025-26,65.0,1961-62 to 2025-26,"2290-2879, .443 W-L%",30,1
36,https://www.basketball-reference.com/teams/ORL,Orlando Magic,"Orlando, Florida",Orlando Magic,37; 1989-90 to 2025-26,37.0,1989-90 to 2025-26,"1356-1529, .470 W-L%",18,0
37,https://www.basketball-reference.com/teams/UTA,Utah Jazz,"Salt Lake City, Utah","Utah Jazz, New Orleans Jazz",52; 1974-75 to 2025-26,52.0,1974-75 to 2025-26,"2194-1920, .533 W-L%",31,0
38,https://www.basketball-reference.com/teams/MIN,Minnesota Timberwolves,"Minneapolis, Minnesota",Minnesota Timberwolves,37; 1989-90 to 2025-26,37.0,1989-90 to 2025-26,"1196-1680, .416 W-L%",13,0
39,https://www.basketball-reference.com/teams/LAC,Los Angeles Clippers,"Los Angeles, California","Los Angeles Clippers, San Diego Clippers, Buff...",56; 1970-71 to 2025-26,56.0,1970-71 to 2025-26,"1893-2549, .426 W-L%",19,0
40,https://www.basketball-reference.com/teams/SAC,Sacramento Kings,"Sacramento, California","Sacramento Kings, Kansas City Kings, Kansas Ci...",78; 1948-49 to 2025-26,78.0,1948-49 to 2025-26,"2788-3299, .458 W-L%",30,1
41,https://www.basketball-reference.com/teams/PHO,Phoenix Suns,"Phoenix, Arizona",Phoenix Suns,58; 1968-69 to 2025-26,58.0,1968-69 to 2025-26,"2465-2142, .535 W-L%",33,0
42,https://www.basketball-reference.com/teams/MEM,Memphis Grizzlies,"Memphis, Tennessee","Memphis Grizzlies, Vancouver Grizzlies",31; 1995-96 to 2025-26,31.0,1995-96 to 2025-26,"1046-1347, .437 W-L%",14,0
43,https://www.basketball-reference.com/teams/NOP,New Orleans Pelicans,"New Orleans, Louisiana","New Orleans Pelicans, New Orleans/Oklahoma Cit...",24; 2002-03 to 2025-26,24.0,2002-03 to 2025-26,"852-998, .461 W-L%",9,0

In [110]:
team_seasons_df=pd.DataFrame(team_seasons_details)

Utilies.make_df_pretty(team_seasons_df)


team_seasons_df

,link,team_full_name,season,record,coach,executive,pts_g,srs,off_rtg,expected_w_l,preseason_odds,arena
0,https://www.basketball-reference.com/teams/OKC...,Oklahoma City Thunder,2024-25,"68-14, Finished 1st in NBA Western Conference",Mark Daigneault (68-14),Sam Presti,120.5 (4th of 30) Opp PTS/G: 107.6 (3rd of 30),12.70 (1st of 30) Pace : 100.0 (6th of 30),120.3 (3rd of 30) Def Rtg : 107.5 (1st of 30) ...,68-14 (1st of 30),"Championship +675 , Over-Under 57.5","Paycom Center Attendance: 754,832 (14th of 30)"
1,https://www.basketball-reference.com/teams/BOS...,Boston Celtics,2023-24,"64-18, Finished 1st in NBA Eastern Conference",Joe Mazzulla (64-18),Brad Stevens,120.6 (2nd of 30) Opp PTS/G: 109.2 (5th of 30),10.74 (1st of 30) Pace : 97.2 (23rd of 30),123.2 (1st of 30) Def Rtg : 111.6 (3rd of 30) ...,66-16 (1st of 30),"Championship +450 , Over-Under 54.5","TD Garden Attendance: 785,396 (10th of 30)"
2,https://www.basketball-reference.com/teams/DEN...,Denver Nuggets,2022-23,"53-29, Finished 1st in NBA Western Conference",Michael Malone (53-29),Calvin Booth,115.8 (12th of 30) Opp PTS/G: 112.5 (8th of 30),3.04 (6th of 30) Pace : 98.1 (23rd of 30),117.6 (5th of 30) Def Rtg : 114.2 (15th of 30)...,49-33 (6th of 30),"Championship +1800 , Over-Under 51.5","Ball Arena Attendance: 788,635 (7th of 30)"
3,https://www.basketball-reference.com/teams/GSW...,Golden State Warriors,2021-22,"53-29, Finished 3rd in NBA Western Conference",Steve Kerr (53-29),Bob Myers,111.0 (15th of 30) Opp PTS/G: 105.5 (3rd of 30),5.52 (4th of 30) Pace : 98.4 (13th of 30),112.5 (17th of 30) Def Rtg : 106.9 (1st of 30)...,55-27 (4th of 30),"Championship +900 , Over-Under 48.5","Chase Center Attendance: 740,624 (10th of 30)"
4,https://www.basketball-reference.com/teams/MIL...,Milwaukee Bucks,2020-21,"46-26, Finished 3rd in NBA Eastern Conference",Mike Budenholzer (46-26),Jon Horst,120.1 (1st of 30) Opp PTS/G: 114.2 (22nd of 30),5.57 (4th of 30) Pace : 102.2 (2nd of 30),117.2 (6th of 30) Def Rtg : 111.4 (10th of 30)...,48-24 (5th of 30),"Championship +550 , Over-Under 49.5","Fiserv Forum Attendance: 64,780 (10th of 30)"
...,...,...,...,...,...,...,...,...,...,...,...,...
114,https://www.basketball-reference.com/teams/DAL...,Dallas Mavericks,2025-26,"0-0, in NBA Western Conference",NaN,NaN,NaN,NaN,NaN,NaN,Championship +3500,American Airlines Center
115,https://www.basketball-reference.com/teams/MEM...,Memphis Grizzlies,2025-26,"0-0, in NBA Western Conference",NaN,NaN,NaN,NaN,NaN,NaN,Championship +15000,FedExForum
116,https://www.basketball-reference.com/teams/HOU...,Houston Rockets,2025-26,"0-0, in NBA Western Conference",NaN,NaN,NaN,NaN,NaN,NaN,Championship +800,Toyota Center
117,https://www.basketball-reference.com/teams/NOP...,New Orleans Pelicans,2025-26,"0-0, in NBA Western Conference",NaN,NaN,NaN,NaN,NaN,NaN,Championship +25000,Smoothie King Center
118,https://www.basketball-reference.com/teams/BOS...,Boston Celtics,2024-25,"61-21, Finished 2nd in NBA Eastern Conference",Joe Mazzulla (61-21),Brad Stevens,116.3 (8th of 30) Opp PTS/G: 107.2 (2nd of 30),8.28 (3rd of 30) Pace : 95.7 (30th of 30),120.6 (2nd of 30) Def Rtg : 111.1 (5th of 30) ...,62-20 (2nd of 30),"Championship +325 , Over-Under 58.5","TD Garden Attendance: 785,396 (8th of 30)"