In [14]:
import pandas as pd

In [15]:
mvp_candidates = pd.read_excel(
    "/Users/anoosha/Projects/Public Github Repos/Data-Analysis-Projects-2-Basketball/data/new_mvp_candidates.xlsx"
)

In [16]:
mvp_candidates

,Year,Rank,Player_Id,Age,Team,First_Place_Vote,Pts Won,pts Max,Share,Games,...,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,2019,1,antetgi01,24,MIL,78,941,1010,0.932,72,...,27.7,12.5,5.9,1.3,1.5,0.578,0.256,0.729,14.4,0.292
1,2019,2,hardeja01,29,HOU,23,776,1010,0.768,78,...,36.1,6.6,7.5,2.0,0.7,0.442,0.368,0.879,15.2,0.254
2,2019,3,georgpa01,28,OKC,0,356,1010,0.352,77,...,28.0,8.2,4.1,2.2,0.4,0.438,0.386,0.839,11.9,0.201
3,2019,4,jokicni01,23,DEN,0,212,1010,0.210,80,...,20.1,10.8,7.3,1.4,0.7,0.511,0.307,0.821,11.8,0.226
4,2019,5,curryst01,30,GSW,0,175,1010,0.173,69,...,27.3,5.3,5.2,1.3,0.4,0.472,0.437,0.916,9.7,0.199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,2025,7T,edwaran01,23,MIN,0,12,1000,0.012,79,...,27.6,5.7,4.5,1.2,0.6,0.447,0.395,0.837,8.4,0.140
81,2025,9,curryst01,36,GSW,0,2,1000,0.002,70,...,24.5,4.4,6.0,1.1,0.4,0.448,0.397,0.933,7.9,0.168
82,2025,10T,brunsja01,28,NYK,0,1,1000,0.001,65,...,26.0,2.9,7.3,0.9,0.1,0.488,0.383,0.821,8.3,0.172
83,2025,10T,hardeja01,35,LAC,0,1,1000,0.001,79,...,22.8,5.8,8.7,1.5,0.7,0.410,0.352,0.874,8.3,0.143
84,2025,10T,mobleev01,23,CLE,0,1,1000,0.001,71,...,18.5,9.3,3.2,0.9,1.6,0.557,0.370,0.725,9.0,0.200

In [17]:
mvp_candidates.columns = mvp_candidates.columns.str.lower()

In [18]:
mvp_candidates_col_names = {
    "first_place_vote": "first_place_votes",
    "pts won": "points_won",
    "pts max": "points_max",
    "fg%": "fg_pct",
    "3p%": "three_pct",
    "ft%": "ft_pct",
    "ws/48": "ws_per_48"
}

In [19]:
mvp_candidates = mvp_candidates.rename(columns=mvp_candidates_col_names)

In [20]:
mvp_candidates[['year','player_id']].duplicated().sum()
##this pair is our composite key

np.int64(0)

In [21]:
split_t = mvp_candidates['rank'].str.strip().str.extract(r'(\d+)(T?)')

In [22]:
split_t

     0  1
0    1
1    2
2    3
3    4
4    5
..  .. ..
80   7  T
81   9
82  10  T
83  10  T
84  10  T

[85 rows x 2 columns]

In [23]:
split_t[1]= split_t[1].astype(bool)

In [24]:
split_t

     0      1
0    1  False
1    2  False
2    3  False
3    4  False
4    5  False
..  ..    ...
80   7   True
81   9  False
82  10   True
83  10   True
84  10   True

[85 rows x 2 columns]

In [25]:
mvp_candidates

,year,rank,player_id,age,team,first_place_votes,points_won,points_max,share,games,...,pts,trb,ast,stl,blk,fg_pct,three_pct,ft_pct,ws,ws_per_48
0,2019,1,antetgi01,24,MIL,78,941,1010,0.932,72,...,27.7,12.5,5.9,1.3,1.5,0.578,0.256,0.729,14.4,0.292
1,2019,2,hardeja01,29,HOU,23,776,1010,0.768,78,...,36.1,6.6,7.5,2.0,0.7,0.442,0.368,0.879,15.2,0.254
2,2019,3,georgpa01,28,OKC,0,356,1010,0.352,77,...,28.0,8.2,4.1,2.2,0.4,0.438,0.386,0.839,11.9,0.201
3,2019,4,jokicni01,23,DEN,0,212,1010,0.210,80,...,20.1,10.8,7.3,1.4,0.7,0.511,0.307,0.821,11.8,0.226
4,2019,5,curryst01,30,GSW,0,175,1010,0.173,69,...,27.3,5.3,5.2,1.3,0.4,0.472,0.437,0.916,9.7,0.199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,2025,7T,edwaran01,23,MIN,0,12,1000,0.012,79,...,27.6,5.7,4.5,1.2,0.6,0.447,0.395,0.837,8.4,0.140
81,2025,9,curryst01,36,GSW,0,2,1000,0.002,70,...,24.5,4.4,6.0,1.1,0.4,0.448,0.397,0.933,7.9,0.168
82,2025,10T,brunsja01,28,NYK,0,1,1000,0.001,65,...,26.0,2.9,7.3,0.9,0.1,0.488,0.383,0.821,8.3,0.172
83,2025,10T,hardeja01,35,LAC,0,1,1000,0.001,79,...,22.8,5.8,8.7,1.5,0.7,0.410,0.352,0.874,8.3,0.143
84,2025,10T,mobleev01,23,CLE,0,1,1000,0.001,71,...,18.5,9.3,3.2,0.9,1.6,0.557,0.370,0.725,9.0,0.200

In [26]:
mvp_candidates[['rank','tie']] = split_t[[0,1]].values

In [27]:
mvp_candidates

,year,rank,player_id,age,team,first_place_votes,points_won,points_max,share,games,...,trb,ast,stl,blk,fg_pct,three_pct,ft_pct,ws,ws_per_48,tie
0,2019,1,antetgi01,24,MIL,78,941,1010,0.932,72,...,12.5,5.9,1.3,1.5,0.578,0.256,0.729,14.4,0.292,False
1,2019,2,hardeja01,29,HOU,23,776,1010,0.768,78,...,6.6,7.5,2.0,0.7,0.442,0.368,0.879,15.2,0.254,False
2,2019,3,georgpa01,28,OKC,0,356,1010,0.352,77,...,8.2,4.1,2.2,0.4,0.438,0.386,0.839,11.9,0.201,False
3,2019,4,jokicni01,23,DEN,0,212,1010,0.210,80,...,10.8,7.3,1.4,0.7,0.511,0.307,0.821,11.8,0.226,False
4,2019,5,curryst01,30,GSW,0,175,1010,0.173,69,...,5.3,5.2,1.3,0.4,0.472,0.437,0.916,9.7,0.199,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,2025,7,edwaran01,23,MIN,0,12,1000,0.012,79,...,5.7,4.5,1.2,0.6,0.447,0.395,0.837,8.4,0.140,True
81,2025,9,curryst01,36,GSW,0,2,1000,0.002,70,...,4.4,6.0,1.1,0.4,0.448,0.397,0.933,7.9,0.168,False
82,2025,10,brunsja01,28,NYK,0,1,1000,0.001,65,...,2.9,7.3,0.9,0.1,0.488,0.383,0.821,8.3,0.172,True
83,2025,10,hardeja01,35,LAC,0,1,1000,0.001,79,...,5.8,8.7,1.5,0.7,0.410,0.352,0.874,8.3,0.143,True
84,2025,10,mobleev01,23,CLE,0,1,1000,0.001,71,...,9.3,3.2,0.9,1.6,0.557,0.370,0.725,9.0,0.200,True

In [28]:
mvp_candidates.columns

Index(['year', 'rank', 'player_id', 'age', 'team', 'first_place_votes',
       'points_won', 'points_max', 'share', 'games', 'mp', 'pts', 'trb', 'ast',
       'stl', 'blk', 'fg_pct', 'three_pct', 'ft_pct', 'ws', 'ws_per_48',
       'tie'],
      dtype='object')

In [29]:
mvp_candidates_col_order = [
    "year",
    "player_id",
    "rank",
    "tie",
    "age",
    "team",
    "first_place_votes",
    "points_won",
    "points_max",
    "share",
    "games",
    "mp",
    "pts",
    "trb",
    "ast",
    "stl",
    "blk",
    "fg_pct",
    "three_pct",
    "ft_pct",
    "ws",
    "ws_per_48",
]

In [30]:
mvp_candidates = mvp_candidates[mvp_candidates_col_order]

In [31]:
mvp_candidates

,year,player_id,rank,tie,age,team,first_place_votes,points_won,points_max,share,...,pts,trb,ast,stl,blk,fg_pct,three_pct,ft_pct,ws,ws_per_48
0,2019,antetgi01,1,False,24,MIL,78,941,1010,0.932,...,27.7,12.5,5.9,1.3,1.5,0.578,0.256,0.729,14.4,0.292
1,2019,hardeja01,2,False,29,HOU,23,776,1010,0.768,...,36.1,6.6,7.5,2.0,0.7,0.442,0.368,0.879,15.2,0.254
2,2019,georgpa01,3,False,28,OKC,0,356,1010,0.352,...,28.0,8.2,4.1,2.2,0.4,0.438,0.386,0.839,11.9,0.201
3,2019,jokicni01,4,False,23,DEN,0,212,1010,0.210,...,20.1,10.8,7.3,1.4,0.7,0.511,0.307,0.821,11.8,0.226
4,2019,curryst01,5,False,30,GSW,0,175,1010,0.173,...,27.3,5.3,5.2,1.3,0.4,0.472,0.437,0.916,9.7,0.199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,2025,edwaran01,7,True,23,MIN,0,12,1000,0.012,...,27.6,5.7,4.5,1.2,0.6,0.447,0.395,0.837,8.4,0.140
81,2025,curryst01,9,False,36,GSW,0,2,1000,0.002,...,24.5,4.4,6.0,1.1,0.4,0.448,0.397,0.933,7.9,0.168
82,2025,brunsja01,10,True,28,NYK,0,1,1000,0.001,...,26.0,2.9,7.3,0.9,0.1,0.488,0.383,0.821,8.3,0.172
83,2025,hardeja01,10,True,35,LAC,0,1,1000,0.001,...,22.8,5.8,8.7,1.5,0.7,0.410,0.352,0.874,8.3,0.143
84,2025,mobleev01,10,True,23,CLE,0,1,1000,0.001,...,18.5,9.3,3.2,0.9,1.6,0.557,0.370,0.725,9.0,0.200

In [33]:
mvp_candidates.dtypes

year                   int64
player_id             object
rank                  object
tie                   object
age                    int64
team                  object
first_place_votes      int64
points_won             int64
points_max             int64
share                float64
games                  int64
mp                   float64
pts                  float64
trb                  float64
ast                  float64
stl                  float64
blk                  float64
fg_pct               float64
three_pct            float64
ft_pct               float64
ws                   float64
ws_per_48            float64
dtype: object

In [34]:
mvp_candidates['rank']=mvp_candidates['rank'].astype('int64')

In [35]:
mvp_candidates['tie']= mvp_candidates['tie'].astype(bool)

In [36]:
mvp_candidates.dtypes

year                   int64
player_id             object
rank                   int64
tie                     bool
age                    int64
team                  object
first_place_votes      int64
points_won             int64
points_max             int64
share                float64
games                  int64
mp                   float64
pts                  float64
trb                  float64
ast                  float64
stl                  float64
blk                  float64
fg_pct               float64
three_pct            float64
ft_pct               float64
ws                   float64
ws_per_48            float64
dtype: object